---
apiVersion: v1
kind: Service
metadata:
  name: argocd-service-node
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32001

